<?php 
$this->view_data = $datas;

$this->view_infos = $infos;

if(empty($this->view_infos))
{
    $this->view_infos = new Book();
}else{
    $book = $this->view_infos;
}

 
?>
<div  class = "row">
    <div  class = "col-md-4 ">
                <?php $alt = $book->getCoverAlt();?>
                <?php $src= IMG . $book->getCover();?>
                <a href="<?php echo HOME?>book-show/show-<?php echo $book->getId()?>"><img  src="<?php echo $src?>" alt="<?php echo $alt?>" title ="<?php echo $alt?>"></a>
    </div>
    <div  class = "col-md-8 ">
        <h1> <?= $book->getTitle();?> </h1>
    </div>
</div>
<?php 
include (VIEW . 'episode\show.phtml');
?>
