        <nav>
        <ul class="nav secondary-nav">
            <li><a href=" <?php echo VIEW ?> login" class = "menu" >Connexion</a></li> 
            <li><a href=" <?php echo VIEW ?> register" class = "menu" >Enregistrement</a></li> 
        </ul>
        </nav>
    </body>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    
    <script type="text/javascript" src="tablesorter.js"></script>
    <script type="text/javascript">
        jQuery(function($) {
            $("table#sortTableExample").tablesorter({ sortList: [[1,0]] });
        });
    </script>
</html>
