
-->
<?php 
$loc = explode(DS,$this->view_file);
$controller = CONTROLLER . $loc[0] . 'controller.php';
$tab = $loc[0];

if(Input::exists())
{ 
    if(Token::check(Input::get('token'))){
        $validate = new validate();  
        $validation = $validate->check($_POST, $tab, array(
        'userId'        => array(
            'Reference' => 'Identifiant',
            'required'  => true,
            'min'       => 2,
            'max'       => 20,
            'unique'    => 'user',
            ),
        'password'      => array(
            'Reference' => 'Mot de passe',
            'required'  => true,
            'min'       => 6
            ),
        'passwordBis'   => array(
            'Reference' => 'Confirmation du Mot de passe',
            'required'  => true,
            'matches'   =>  'password'
        ),
        'email'         => array(
            'Reference' => 'Adresse mail',
            'required'  => false
        ),
        'lastName'      => array(
            'Reference' => 'Nom ',
            'required'  => false,
            'max'       => 50
        ),
        'pseudo'        => array(
            'Reference' => 'Pseudo',
            'required'  => false,
            'max'       => 50
        )
        ));
        if($validate->passed()){
            // register user
          //  Session::flash('success', 'you registered successfully' );
            $user = new User();
            $salt = Hash::salt(32);
           
           try{
                $user->create(array(
                'id'        => null,
                'userId'    => Input::get('userId'),
                'password'  => Hash::make(Input::get('password'),$salt),
                'salt'      => $salt,
                'email'     => Input::get('email'),
                'lastName'  => Input::get('lastname'),
                'pseudo'   =>  Input::get('pseudo'),
                'joigned'  =>  date('Y-m-d H:i:s'),  
                'groupId'  => '10'
                ));
                Session::flash('home', 'you registered successfully and can now loggin' );
                // header('location: index.phtml');
                Redirect::to('index.phtml');
           } catch(Exception $e){
               die($e->getMessage());
           }
        } else {
            // output errrors
                  
            foreach($validate->errors() as $error){
                echo '<br/>',  $error, '<br/>';
            }
            echo '<br/>';
        }
    }   
}
 
 ?>
 <?php $opt = "register"; ?>
<?php $class = 'class = "form-control form-control-sm"'; ?>

<form  action ="<?= HOME . 'index.php' ?>" method = "post">

<form action = ""  method = "post">
<div class="row">  
<div class = "col-md-6 offset-md-1">
    <div class="form-group">
    
        <label for "userId">Identifiant</label>
        <input <?= $class; ?> type="text" name="userId" id="userId" value="<?php escape(Input::get('userId')); ?>" autocomplete="off">
    </div>

    <div class="form-group">
    <label for "password">Mot de passe</label>
    <input <?= $class; ?> type="password" name="password" id="password" value="<?php escape(Input::get('password')); ?>" autocomplete="off">
    </div>

    <div class="form-group">
    <label for "passwordBis">Confirmer le Mot de passe</label>
    <input <?= $class; ?> type="password" name="passwordBis" id="passwordBis" value="" autocomplete="off">
    </div>

    <div class="form-group">
    <label for "email">Adresse Mail</label>
    <input <?= $class; ?> type="e-mail" name="email" id="email" value="" autocomplete="off">
    </div>

    <div class="field">
    <label for "lastName">Nom</label>
    <input <?= $class; ?> type="text" name="lastName" id="lastName" value="" autocomplete="off">
    </div>

    <div class="field">
    <label for "pseudo">Pseudo</label>
    <input <?= $class; ?> type="text" name="pseudo" id="pseudo" value="" autocomplete="off">
    </div>
   
    <input type="hidden" name="url" value ="<?= 'user/edit-'; ?>"> 
    
    <input type='hidden' name="action" value ="<?php echo($opt); ?>">
    <input type="hidden" name="token" id="token" value="<?php // echo Token::generate(); ?>">
    <input type="submit" value="inscription">
    </div>
    </div>
    </div>
</form>

