    
       

      

        <footer>          
            <div class="row">   
               
                    <?php if(isset($this->view_footerData)) : ?>
                        <h5>A découvrir en Librairie, sur Amazon ou ailleurs</h5>
                        <div class = "container-fluid">
                            <div id="out_there" class="card-deck-wrapper">
                                <div class="row">
                                <div class = "col-md-12">
                                    <div  class="card-deck">
                                        <?php foreach($this->view_footerData as $book): ?>
                                            <?php $accesBook = HOME . 'book-show/show-' ?>
                                            <?php $id = $book->getId(); ?>
                                            <?php $src = IMG215 . $book->getCover() ;?> 
                                            <?php $title = $book->getTitle() ?> 
                                            <?php $editeur = "ND  " . $book->getEditYear() ?> 
                                            <?php  include('card.phtml'); ?>
                                        <?php endforeach; ?>
                                    </div>
                            </div>
                               </div>
                            </div>
                        </div>
                    <?php endif; ?>
                
            </div>
            <hr/>
            <div class="row">
                <div class="col-md-6"> 
                    <nav class="row">
                        <ul class="nav secondary-nav">   
                                <?php include('navmnu.phtml'); ?>
                        </ul>
                    </nav>
                </div>
                <div class="col-md-6"> 
                    <ul class="nav secondary-nav">
                        <li><a href="#" target="_blank"> - Copyright © 2019  <?php echo HOME?> </a></li>     
                        <li><a href="#" target="_blank"> - Politique de confidentialité </a></li>   
                        <li><a href="#" target="_blank"> - Design & developpement</a></li>    
                    </ul>
                </div>
             </div>

        </footer>  
   
   
        <script type="text/javascript" src="http://localhost/jfrblog/js/tablesorter.js"></script>
        <script type="text/javascript">
            jQuery(function($) {
                $("table#sortTableExample").tablesorter({ sortList: [[1,0]] });
            });
        </script>
        <script>$(document).ready(function(){$('[data-toggle="tooltip"]').tooltip();});</script>
        <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js"></script>  
        <script>tinymce.init({selector:".tinymce"})</script>
     <!--   <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script> -->
        </div>
    </body>
</html>
