    
       

      
    <div class ="container"> 
        <footer>
            <div class="row">
                <nav class="row">
                    <div class="col-md-8">  
                        
                    <!-- //   <img src="https://picsum.photos/100/150" alt="Dernière actu " /> -->
                    <li> <a href="<?php echo HOME?>book"><img src="<?php echo HOME?>img/Totem_pole_min.jpg" alt ="XXX" title ="Totem"></a></li>
                   <li> <a href="<?php echo HOME?>book"><img src="<?php echo HOME?>img/author_at_work_min.jpg" alt ="XXX" title ="Dame venue du Sud"></a></li>
                   <li> <a href="<?php echo HOME?>book"><img src="<?php echo HOME?>img/haida_haash_min.jpg" alt ="XXX" title ="Haïda"></a></li>
                   <li> <a href="<?php echo HOME?>book"><img src="<?php echo HOME?>img/tingit.jpg" alt ="XXX" title ="Oiseau"></a></li>
                   <li> <a href="<?php echo HOME?>book"><img src="<?php echo HOME?>img/Chief_cow_dic_ney_min.jpg" alt ="XXX" title ="Maître d'O"></a></li>
                    
                   <li> <a href="<?php echo HOME?>book"><img src="<?php echo HOME?>img/wolf_housepost_tlingit_min.jpg" alt ="XXX" title ="Dame venue du Sud"></a></li>
</div>
                </nav>
                <div class="col-md-4"> 
                    <nav class="row">
                        <ul class="nav secondary-nav">       
                            <li><a href="<?php echo HOME?>home"> Accueil </a></li>
                            <li><a href="<?php echo HOME?>book"> Livres </a></li> 
                            <li><a href="<?php echo HOME?>blog"> Blog </a></li> 
                            <li><a href="<?php echo HOME?>movie"> Films </a></li> 
                            <li><a href="<?php echo HOME?>aboutJFR"> A propos </a></li>
                        </ul>
                    </nav>  
                    <div class="row">
                    <ul class="nav secondary-nav">       
                            <li><a href="<?php echo HOME?>login" class = "menu" > Connexion </a></li> 
                            <li><a href="<?php echo HOME?>register" class = "menu" > Enregistrement</a></li> 
                        </ul>
                        </div>
                </div>
            </div>
            
            
              
           
        </footer>  
    </div>
    
     
    </body>
    <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script type="text/javascript" src="http://localhost/jfrblog/js/tablesorter.js"></script>
    <script type="text/javascript">
        jQuery(function($) {
            $("table#sortTableExample").tablesorter({ sortList: [[1,0]] });
        });
    </script>
    <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js"></script>  
    <script>tinymce.init({selector:"textarea.tinymce"})</script>
   <!--        
        <script src="<?php echo HOME?>plugin/tinymce/tinymce.min.js"></script>
        <script src="<?php echo HOME?>plugin/tinymce/init-tinymce.js"></script>   
        --> 
</html>
