<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="utf-8" />
    <!-- ??? <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">--> 
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="robots" content="noindex">
    <meta name="googlebot" content="noindex">
    <!-- <link rel="stylesheet" href="?php CSS;?>bootstrap.css"> --> 
    <title><?= $title ?? "JFR blog";?></title> 
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    
    <script src="https://use.fontawesome.com/releases/v5.7.0/js/all.js"></script>    
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

    <link rel="stylesheet" href="<?php echo HOME?>style.css">     
  </head>
  <?php   $action = $this->getAction();?>
  <body>
    <div class = "container-fluid">
    <!-- Navigation -->   
      <header>
        <nav class = "navbar navbar-expand-md navbar-light bg-light sticky-top">
          <div class ="container-fluid">  
            
              <a class="navbar-brand" href="<?php echo HOME?>home"><img class="img-responsive" src="<?php echo IMG125?>J.jpg"  alt ="JFR"></a><h2>ean FORTEROCHE</h2>
           
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
              <ul class="navbar-nav ml-auto">
                <?php include('navmnu.phtml'); ?>
              </ul>
            </div>  
          </div>
         
          <?php if(isset($this->view_headerData)) :
            
            foreach($this->view_headerData as $book)
            {
              $src= IMG . $book->getCover();
              $alt="Portail de glace";
              $cardTitle ="Dernier billet";
              $cardSubTitle=" ...pour l'Alaska";
                
            }
          ?>
            <div id ="thema" class = "card">
                <img class ="card-img-body" src="<?php echo $src?>" alt="<?php echo $alt?>" title ="<?php echo $alt?>">  
                <div class="card-img-overlay">
                  <h3 class="card-title"><?php echo $cardTitle?> </h3>
                  <h4 style="text-align:right"> <?php echo $cardSubTitle?></h4>
                </div>
            </div> 
          <?php endif; ?>  
        </nav>            
      </header>
 