<?php
$action = $this->getAction();
?>
<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="utf-8">
          <!-- <link rel="stylesheet" href="<?php CSS;?>bootstrap.css"> --> 
        <link rel="stylesheet" href="https://getbootstrap.com/1.4.0/assets/css/bootstrap.min.css">
        <link rel="stylesheet" href="http://localhost/jfrblog/style.css">
        
        <title> JFR blog</title>
        
    </head>
   
   
    <body>
      <nav>
        <ul>
          <li><a href="home" <?php echo($action == 'index' ? 'class="active"' :''); ?>>Home</a></li>
          <li><a href="\jfrblog/book" <?php echo($action =='book' ? 'class="active"' : '') ; ?>>Bibliographie</a></li> -->
          <li><a href="home/aboutJFR" <?php echo($action =='aboutJFR' ? 'class="active"' : '') ; ?>>About JFR</a></li>
        </ul>
      </nav>