<?php include(VIEW . 'header.phtml'); ?>
        <div class = "container-fluid">
            <div class="row">  
                
                <div class ="col-md-12">    
    
                    <?php  if(Session::exists('errors') ):?>

                        <?php foreach(Session::get('errors') as $error):?>
                            <li><?= $error;?></li>
                        <?php endforeach;?>
                        <?php Session::delete('errors');?>
                    <?php endif;?>
                    <section>
                        <h1><?=$this->page_title?></h1>
                        <?php  echo $contentPage; ?>
                    </section>
                </div>
                
            </div>
        </div>
        <hr/>
<?php include(VIEW . 'footer.phtml'); ?>