<?php include(VIEW . 'header.phtml'); ?>
        <div class = "container-fluid">
            <div class="row">  
                
                <div class ="col-md-10">    
    
                    <?php  if(isset($_SESSION['errors']) && !empty($_SESSION['errors']) ):?>

                    <?php foreach($_SESSION['errors'] as $error):?>
                        <li><?= $error;?></li>
                    <?php endforeach;?>
                    <?php unset($_SESSION['errors']);?>
                    <?php endif;?>
                    <section>
                        <h1><?=$this->page_title?></h1>
                        <?php  echo $contentPage; ?>
                    </section>
                </div>
                <nav class="col-md-2">
                    <ul>
                        <li> <a href="<?php echo HOME?>book"><img class="img-thumbnail" src="<?php echo HOME?>img/Totem_pole_min.jpg" alt ="XXX" title ="Totem"></a></li>
                        <li> <a href="<?php echo HOME?>book"><img class="img-thumbnail" src="<?php echo HOME?>img/haida_haash_min.jpg" alt ="XXX" title ="Haïda"></a></li>
                        <li> <a href="<?php echo HOME?>book"><img class="img-thumbnail" src="<?php echo HOME?>img/tingit.jpg" alt ="XXX" title ="Oiseau"></a></li>
                        <li> <a href="<?php echo HOME?>book"><img class="img-thumbnail" src="<?php echo HOME?>img/Chief_cow_dic_ney_min.jpg" alt ="XXX" title ="Maître d'O"></a></li>
                   </ul> 
                </nav>
            </div>
        </div>
<?php include(VIEW . 'footer.phtml'); ?>