<?php include(VIEW . 'header.phtml'); 
$books = $this->view_data;
$book = $books[0];
?>
<h1> Book management </h1>
<!--SELECT `id``title``plot``onlineDat``nbEps``status``isbn``editYear` FROM `book` -->
<h2> Show book detail </h2>
<form class ="dta-add-class" action ="bookManager">
    <div class="input">                 
            <label>Titre </label> :<input type="text" name="title" maxlength=30 value="<?=$book->title ?>">
    </div>
    <div class="input">  
        <label for="plot">résumé</label>
        <textarea  name = "infos" value="<?=$book->plot ?>" cols= 120 rows = 5> </textarea wrap="type">
    </div>
    <div class="input">  
        <label>Status </label> :<input type="text" name="status" value="<?=$book->status ?>"maxlength=2>
    </div>
    <div class="input">                 
        <label>ISBN </label> :<input type="text" name="isbn" value="<?=$book->isbn ?>"maxlength=20>
    </div>
    <div class="input">                 
        <label>Année edition </label> :<input type="number" name="editYear" value="<?=$book->editYear ?>"placeholder="SSAA" maxlength=4>
    </div>
    <input type='hidden' name="id" value="<?=$book->id ?>">
    <input type='hidden' name='addBook' value='yes'>
    <div class="input">  
        <input type="submit" value ="MODIFIER">
    </div>
</form>



        

        
        

        


<?php include(VIEW . 'footer.phtml'); ?>