
<?php $this->view_data =$datas ;  ?>

<?php  if(isset($_SESSION['errors']) && !empty($_SESSION['errors']) ):?>

    <ul>
    <?php foreach($_SESSION['errors'] as $error):?>
            <li class = "alert"><?= $error;?></li>
    <?php endforeach;?>
    <?php unset($_SESSION['errors']);?>
    </ul>
<?php endif;?>

<?php  foreach($this->view_data as $book) : ?>
<!--SELECT `id``title``plot``onlineDat``nbEps``status``isbn``editYear` FROM `book` -->
    <h2><?=($book->getId()) > 0 ? $book->getTitle() : ' '; ?> </h2>
    <br>
    <div class="container">
        <form class ="dta-add-class" action ="<?= HOME . 'index.php' ?>" method = "post">
      
            <p><?php $label = "Titre..............:";?>                 
                <label><?=$label?></label><input class="form-control" type="text" name="title"  value="<?=($book->getId()) > 0 ? $book->getTitle() : ' '; ?> "   maxlength="50"  />
            </p>
            
            <div id="myeditablediv"><?php $label = "Résumé.............:";?>
                <label for="plot"> <?=$label?></label>
                <textarea  class="tinymce" name = "plot" cols= 80 rows = 10 required > <?=($book->getId()) > 0 ? $book->getPlot(): ''; ?> </textarea wrap="type">
            </div>

            <p><?php $label = "Status.............:";?>  
                <label><?=$label?></label><input class="form-control" type="text" name="status" value="<?=($book->getId()) > 0 ? $book->getStatus():''; ?>"maxlength="2" />
            </p>  

            <p><?php $label = "ISBN...............:";?>                 
                <label><?=$label?></label><input class="form-control" type="text" name="isbn" value="<?=($book->getId()) > 0 ? $book->getIsbn():''; ?>"maxlength="20"  />
            </p>

            <p><?php $label = "Année edition......:";?>                 
                <label><?=$label?></label><input class="form-control" type="number" maxlength="4" name="editYear" value="<?=($book->getId()) > 0 ? $book->getEditYear():''; ?>"placeholder="SSAA" maxlength=4/>
            </p>

            <p> 
            <?php $dat = ($book->getOnlineDat() !== null ? $book->getOnlineDat()->format("Y-m-d H:i:s") : ''); ?>
            <label><?= $book->getOnlineDatLabel()?></label><input class="form-control" type="<?=$book->getOnlineDatType();?>"  name="onlineDat" value="<?=($book->getId()) > 0 ? $dat : '';  ?>"  readOnly />
        
            <p> 
                      
                <label><?=$book->getNbEpisodesLabel();?></label><input class="form-control" type="<?=$book->getNbEpisodesType();?>" maxlength="3" name="nbEps" value="<?= ($book->getId()) > 0 ? $book->getNbEpisodes() : ''; ?>" readOnly />
            </p>
            <p> 
                <?php if($book->getStatus() >= '30')
                {
                    $label = "Couverture........:";
                    $type  = "text";
                }else{
                    $label ="";
                    $type  = "hidden";
                }
              
                ?>                   
                <label><?=$label?></label><input class="form-control" type="<?=$type;?>" maxlength="30" name="cover" value="<?= ($book->getId()) > 0 ? $book->getCover() : ''; ?>" />
            </p>
            <p> 
                <?php if($book->getStatus() >= '30')
                {
                    $label = "Légende...........:";
                    $type  = "text";
                }else{
                    $label ="";
                    $type  = "hidden";
                }
                ?>                   
                <label><?=$label?></label><input class="form-control" type="<?=$type;?>" maxlength="50" name="coverAlt" value="<?= ($book->getId()) > 0 ? $book->getCoverAlt() : ''; ?>" />
            </p>
            <p> 
                <?php if($book->getStatus() >= '30')
                {
                    $label = "Mise en avant.....:";
                    $type  = "text";
                }else{
                    $label ="";
                    $type  = "hidden";
                }
                ?>                   
                <label><?=$label?></label><input class="form-control" type="<?=$type;?>" maxlength="1" name="promoted" value="<?= ($book->getId()) > 0 ? $book->getPromoted() : 0; ?>" />
            </p>

            <p> 
                
                <?php $label = "Mise en avant.....:"; ?>                  
                <label><?=$label?></label><input class="form-control" type="number" maxlength="1" name="blogged" value="<?= ($book->getId()) > 0 ? $book->getBlogged() : 0; ?>" />
            </p>
            <input type="hidden" name="lastVolPrt" value="<?= ($book->getId()) > 0 ? $book->getLastVolPrt() : 0; ?>">
            <input type="hidden" name="id" value="<?= ($book->getId()) > 0 ? $book->getId() :''; ?>">
            <input type="hidden" name="url" value ="<?= 'book/edit-' . ($book->getId() > 0 ? $book->getId() .'-' . 'maj' :'') ; ?>"> 
            <input type='hidden' name="action" value ="maj">
            
            <br>
            <input class="pull-right" type="submit" value =" <?=$book->getId() > 0 ? 'MODIFIER' : 'AJOUTER' ; ?>" /> 
     
        </form>
    </div>
<?php endforeach ?>