<?php include(VIEW . 'header.phtml'); 

var_dump($this);
$btn = $this->button_value;
$opt = $this->page_opt;
$readOnly = null;
var_dump($btn);
if( $this->page_opt == 'none' or  $this->page_opt == 'visu' or $this->page_opt == 'del')
{
    $readOnly = (string) 'readOnly';
}
if(empty($this->view_data))
{
    $this->view_data = new Book();
    // $book = new Book();
}
foreach($this->view_data as $book)
{  
?>
<h1> Book management </h1>
<!--SELECT `id``title``plot``onlineDat``nbEps``status``isbn``editYear` FROM `book` -->
<h2> <?=$this->page_title?> </h2>
<form class ="dta-add-class" action ="<?= HOME . 'index.php' ?>" method = "post">
    <div class="input">                 
        <label>Titre </label> :<input type="text" name="title"  value="<?=($book->getId()) > 0 ? $book->getTitle() : ' '; ?> "   maxlength="50"  <?=$readOnly;?>/>
    </div>
    <div class="input">  
        <label for="plot">résumé</label>
        <textarea  name = "plot" cols= 120 rows = 5 required <?=$readOnly;?>> <?=($book->getId()) > 0 ? $book->getPlot(): ''; ?> </textarea wrap="type" >
    </div>
    <div class="input">  
        <label>Status </label> :<input type="text" name="status" value="<?=($book->getId()) > 0 ? $book->getStatus():''; ?>"maxlength="2" <?=$readOnly;?>/>
    </div>
    <div class="input">                 
        <label>ISBN </label> :<input type="text" name="isbn" value="<?=($book->getId()) > 0 ? $book->getIsbn():''; ?>"maxlength="20"  <?=$readOnly;?>/>
    </div>
    <div class="input">                 
        <label>Année edition </label> :<input type="number" maxlength="4" name="editYear" value="<?=($book->getId()) > 0 ? $book->getEditYear():''; ?>"placeholder="SSAA" maxlength=4 <?=$readOnly;?>/>
    </div>
    <div class="input">                 
        <label>Mis en ligne le </label> :<input type="date" maxlength="10" name="onlineDat" value="<?=($book->getId()) > 0 ? $book->getOnlineDat(): '';  ?>"  <?=$readOnly;?>/>
    </div>
    <div class="input">                 
        <label>Nb épisodes </label> :<input type="number" maxlength="3" name="nbEps" value="<?= ($book->getId()) > 0 ? $book->getnbEps() : ''; ?>" <?=$readOnly;?>/>
    </div>
    <input type="hidden" name="id" value="<?= ($book->getId()) > 0 ? $book->getId() :''; ?>">
   <input type="hidden" name="url" value ="<?= 'book/edit-' . ($book->getId() > 0 ? $book->getId() .'-' . $opt :'') ; ?>"> 
    <input type='hidden' name="action" value ="<?php echo($opt); ?>">
    <div class="input">  
      <input type="<?= $btn == 'none' ? 'hidden' : 'submit' ?>" value =" <?= $btn; ?>" /> -->
    </div>
</form>

<?php
}
?>


        

        
        

        


<?php include(VIEW . 'footer.phtml'); ?>