<?php 
$btn = $this->button_value;
$opt = $this->page_opt;
$readOnly = null;
if( $this->page_opt == 'none' or  $this->page_opt == 'visu' or $this->page_opt == 'del')
{
    $readOnly = (string) 'readOnly';
}
?>
<?php  if(isset($_SESSION['errors']) && !empty($_SESSION['errors']) ):?>

    <ul>
    <?php foreach($_SESSION['errors'] as $error):?>
            <li class = "alert"><?= $error;?></li>
    <?php endforeach;?>
    <?php unset($_SESSION['errors']);?>
    </ul>
<?php endif;?>
<?php var_dump($this); die; ?>
<?php 
if(isset($infos) && is_array($infos))
{
    $Xeps = count($infos);
}
foreach($this->view_data as $book)
{ 
?>
<!--SELECT `id``title``plot``onlineDat``nbEps``status``isbn``editYear` FROM `book` -->
<h2><?=($book->getId()) > 0 ? $book->getTitle() : ' '; ?> </h2>
<br>
<div class="container">
    <form class ="dta-add-class" action ="<?= HOME . 'index.php' ?>" method = "post">
      
            <p><?php $label = "Titre..............:";?>                 
                <label><?=$label?></label><input class="form-control" type="text" name="title"  value="<?=($book->getId()) > 0 ? $book->getTitle() : ' '; ?> "   maxlength="50"  <?=$readOnly;?>/>
            </p>
            
            <div id="myeditablediv"><?php $label = "Résumé.............:";?>
                <label for="plot"> <?=$label?></label>
                <textarea  class="tinymce" name = "plot" cols= 150 rows = 10 required <?=$readOnly;?>> <?=($book->getId()) > 0 ? $book->getPlot(): ''; ?> </textarea wrap="type">
            </div>

            <p><?php $label = "Status.............:";?>  
                <label><?=$label?></label><input class="form-control" type="text" name="status" value="<?=($book->getId()) > 0 ? $book->getStatus():''; ?>"maxlength="2" <?=$readOnly;?>/>
            </p>  

            <p><?php $label = "ISBN...............:";?>                 
                <label><?=$label?></label><input class="form-control" type="text" name="isbn" value="<?=($book->getId()) > 0 ? $book->getIsbn():''; ?>"maxlength="20"  <?=$readOnly;?>/>
            </p>

            <p><?php $label = "Année edition......:";?>                 
                <label><?=$label?></label><input class="form-control" type="number" maxlength="4" name="editYear" value="<?=($book->getId()) > 0 ? $book->getEditYear():''; ?>"placeholder="SSAA" maxlength=4 <?=$readOnly;?>/>
            </p>

            <p>
                <?php if($book->getStatus() == '30')
                {
                    $label = "Mis en ligne le....:";
                    $type  = "date";
                }else{
                    $label ="hors ligne";
                    $type  = "hidden";
                }
                ?>                 
                <label><?=$label?></label><input class="form-control" type="<?=$type;?>" maxlength="10" name="onlineDat" value="<?=($book->getId()) > 0 ? $book->getOnlineDat(): '';  ?>"  <?=$readOnly;?>/>
            </p>

            <p> 
                <?php if($book->getStatus() == '30')
                {
                    $label = "Nb épisodes........:";
                    $type  = "number";
                }else{
                    $label ="";
                    $type  = "hidden";
                }
                ?>                   
                <label><?=$label?></label><input class="form-control" type="<?=$type;?>" maxlength="3" name="nbEps" value="<?= ($book->getId()) > 0 ? $Xeps : ''; ?>" <?=$readOnly;?>/>
            </p>
            <p> 
                <?php if($book->getStatus() == '30')
                {
                    $label = "Couverture........:";
                    $type  = "text";
                }else{
                    $label ="";
                    $type  = "hidden";
                }
                ?>                   
                <label><?=$label?></label><input class="form-control" type="<?=$type;?>" maxlength="30" name="cover" value="<?= ($book->getId()) > 0 ? $book->getCover() : ''; ?>" <?=$readOnly;?>/>
            </p>
            <p> 
                <?php if($book->getStatus() == '30')
                {
                    $label = "Légende...........:";
                    $type  = "text";
                }else{
                    $label ="";
                    $type  = "hidden";
                }
                ?>                   
                <label><?=$label?></label><input class="form-control" type="<?=$type;?>" maxlength="50" name="coverAlt" value="<?= ($book->getId()) > 0 ? $book->getCoverAlt() : ''; ?>" <?=$readOnly;?>/>
            </p>
            <p> 
                <?php if($book->getStatus() == '30')
                {
                    $label = "Mise en avant.....:";
                    $type  = "text";
                }else{
                    $label ="";
                    $type  = "hidden";
                }
                ?>                   
                <label><?=$label?></label><input class="form-control" type="<?=$type;?>" maxlength="1" name="promoted" value="<?= ($book->getId()) > 0 ? $book->getPromoted() : ''; ?>" <?=$readOnly;?>/>
            </p>

            <input type="hidden" name="id" value="<?= ($book->getId()) > 0 ? $book->getId() :''; ?>">
            <input type="hidden" name="url" value ="<?= 'book/edit-' . ($book->getId() > 0 ? $book->getId() .'-' . $opt :'') ; ?>"> 
            <input type='hidden' name="action" value ="<?php echo($opt); ?>">
            
            <br>
            <input class="pull-right" type="<?= $btn == 'none' ? 'hidden' : 'submit' ?>" value =" <?= $btn; ?>" /> 
     
    </form>
</div>

<?php
}
?>


        

        
        

        


