<div  class = "row">

    <div  class = "col-md-2">
        <?php $accesBook = HOME . 'book-show/show-' . $book->getId(); ?>
        <a href="<?php echo $accesBook ?>"><img  src="<?php echo IMG215 . $book->getCover()?>" alt="<?php echo $book->getCoverAlt()?>" title ="<?php echo $book->getCoverAlt()?>"></a>
      
    </div>
    <div  class = "col-md-9 offset-md-1">
        <h2><?php  echo $book->getTitle(); ?>
            <?php if($book->getStatus() === '20'): ?>
                <p><i class="fas fa-dragon" alt="Avant première" title = "just for friends"></i></p>   
            <?php endif; ?> 
        </h2>
        <div  class = "row">
            <div  class = "col-md-8 ">
            <p><?php  echo $book->getPlot(); ?></p>
            </div>
            <?php if($book->getEpisodes() !== null) :  ?> 
                <div  class = "col-md-2">
                    <?php $src= IMG . "attrapeur-reve_min70";?>           
                    <a href="<?php echo $accesBook ?>"><img  src="<?php echo $src?>" alt="?" title ="Tous les épisodes"></a>
                </div>
            <?php endif; ?>
        </div>
    </div>
</div>