<?php include(VIEW . 'header.phtml'); ?>
<h1> Show book list </h1>
<div>
    <li><a href= " <?php APP . '/book/edit' ?> ">Ajouter</a></li>
</div>

<div id="container" class="row">
    <table class="table-striped" >
        <thead>
            <tr>
                <th>Titre</th>
                <th>Intrigue</th>
                <th>Isbn</th>
                <th>Année ed°</th>
                <th>Der.mise en ligne</th>
                <th>Nb.Episode</th>
                <th>voir +</th>
            </tr>
        </thead>
        <tbody>

            <?php 
            // var_dump( $this->view_data);
            $table = '';
            foreach($this->view_data as $book)
            { 
                $table .= '<tr>';
                // var_dump($book);
                $table .= '<td>' . $book['title'] . '</td>';
                $table .= '<td>' . $book['plot'] . '</td>';
                $table .= '<td>' . $book['isbn'] . '</td>';
                $table .= '<td>' . $book['editYear'] . '</td>';
                $table .= '<td>' . $book['onlineDat']  . '</td>';
                $table .= '<td>' . $book['nbEps']   . '</td>';
                $table .= '<td>' . '<a href= "\jfrblog/book/edit' . $book['id'] . '">Visu</a>' . '</td>';
                $table .= '<tr>';
            }
            print_r($table);
            
            ?>
        <tbody>
    </table>
</div>
<?php include(VIEW . 'footer.phtml'); ?>