<h1> Show book list </h1>
<div>
    <li><a href= " <?php HOME ?> book/edit-">Ajouter un livre</a></li>
</div>

<div id="container" class="row">
    <div class="table-responsive">
        <table class="table-striped" >
            <thead>
                <tr>
                    <th>Titre</th>
                    <th>Intrigue</th>
                    <th>Statut</th>
                    <th>Couveture</th>
                    <th>Nb.Episode</th>
                    <th>voir +</th>
                </tr>
            </thead>
            <tbody>

                <?php 

                $table = '';
                foreach($this->view_data as $book)
                {                
                    $src= IMG125 . $book->getCover();                                                                                                                                                                                                        
                    $table .= '<tr>';
                    $table .= '<td><a href= "' . HOME . 'episode/index-'. $book->getId() .'">' . $book->getTitle() . '</a></td>';
                    $table .= '<td>' . $book->getPlot() . '</td>';
                    $table .= '<td>' . $book->getStatus() . '</td>';
                    $table .= '<td><img src="' .  $src . '" alt="'. $book->getCoverAlt() . '" title ="' . $book->getCoverAlt() . '"></td>';
                    $table .= '<td>' . $book->getNbEps()   . '</td>';
                    $table .= '<td><a href='.'book/edit-' . $book->getId() . '>Visu</a></td>';
                    $table .= '<td><a href='.'book/edit-' . $book->getId() . '-upd' . '>Maj</a></td>';
                    if($book->getStatus() > '00' && $book->getStatus() < '30')
                    {
                        $table .= '<td><a href='.'book/edit-' . $book->getId() . '-del' . '>Del</a></td>';
                    }

                    $table .= '<tr>';
                }
                print_r($table);
                

                ?>
            <tbody>
        </table>
    </div>
</div>
