
<?php $this->view_data = $datas ; ?>
<!-- `id``bookId``bookVol``bookChap``epsId``user``pseudo``comment``postDat``status``validDat` -->

    <?php $comments = $this->view_data;  ?>
    <?php $comment = $comments[0]; ?>
    <?php $books = $comment->getBookInfo();  ?>
    <?php $book = $books[0]  ?>
    
    <?php include (VIEW . 'book\entBook.phtml'); ?>

    <table class="table table-striped" >
        <thead class="thead-light">
            <tr>
                <th>Chapître</th>
                <th>Visiteur </th>
                <th>le:</th>
                <th class = "clsText">commentaire</th>
                <th>statut</th>
                <th>Revalidé le</th>
                <th>Nv.<i class="fas fa-thumbs-down" alt="Nouveaux signalement versus total" title = "Nouveaux signalement/ total"></i>/total</th>
                <th>Alt</th>
                <th>OK</th>
                <th>NOK</th>
            </tr>
        </thead>
        <tbody>
            <p>
            <?php 
            $table = '';
            foreach($this->view_data as $comment)
            {               
                $episodes = $comment->getEpisodeInfo(); 
                $episode = $episodes[0] ;
                $refComm = $comment->getBookId() . '.' . $comment->getEpsId() .  '.' . $comment->getId();                                                                                                                                                                                                 
                $table .= '<tr>';               
                $table .= '<td>' . $episode->getChapter() . '</td>';
                $table .= '<td>' . $comment->getPseudo()  . '</td>';
                $table .= '<td>' . ($comment->getPostDat() !== null ? $comment->getPostDat()->format("d-m-Y H:i:s" ) : '') . '</td>';
                $table .= '<td class = "clsText">' . $comment->getComment() . '</td>';
                $table .= '<td>' . $comment->getStatus()  .  '</td>';
                $table .= '<td>' . ($comment->getValidDat() !== null ? $comment->getValidDat()->format("d-m-Y") : '') . '</td>';
                $table .= '<td>' . $comment->getNewCon()   . '/' . $comment->getNbCon()   . '</td>';
                $table .= '<td><i class="fas fa-bell" alt="Alerte Commentaire" title = "Alerte Commentaire"></i></td>';
                $table .= '<td><a href="'. HOME .'comment-gest/val-' . $comment->getId() . '-upd' .'"><i class = "fas fa-thumbs-up " alt="Valider commentaire" title = "Validation"></i></a></td>';
                $table .= '<td><a  href="'. HOME . 'comment-gest/del-' . $comment->getId()  . '-del' . '"><i class = "fas fa-comment-slash " alt="Supprimer commentaire" title = "Suppression"></i></a></td>';
                
                 /* $table .= '<td>' . '<input type="hidden" name="T$comment" value ="<?php $comment; ?>"/>' . '</td>'; */

                $table .= '<tr>';
            }
            print_r($table);
           
            ?>
             <p>
        <tbody>
    </table>
