
<?php $this->view_data = $datas ; ?>
<!-- `id``bookId``bookVol``bookChap``epsId``user``pseudo``comment``postDat``status``validDat` -->
<div id="container" class="row">
    <?php $comments = $this->view_data;  ?>
    <?php $comment = $comments[0]; ?>
    <?php $books = $comment->getBookInfo();  ?>
    <?php $book = $books[0]  ?>
    
    <?php include (VIEW . 'book\entBook.phtml'); ?>

    <table class="table-striped" >
        <thead>
            <tr>
                <th>Chapître</th>
                <th>Visiteur </th>
                <th>le:</th>
                <th>commentaire</th>
                <th>statut</th>
                <th>Image<br/> Vue </th>
                <th>Der.commentaire</th>
                <th>voir +</th>
            </tr>
        </thead>
        <tbody>
            <p>
            <?php 
            $table = '';
            foreach($this->view_data as $comment)
            {               
                $episodes = $comment->getEpisodeInfo(); 
                $episode = $episodes[0] ;
                $refComm = $comment->getBookId() . '.' . $comment->getEpsId() .  '.' . $comment->getId();                                                                                                                                                                                                 
                $table .= '<tr>';               
                $table .= '<td>' . $episode->getChapter() . '</td>';
                $table .= '<td>' . $comment->getPseudo()  . '</td>';
                $table .= '<td>' . $comment->getPostdat() . '</td>';
                $table .= '<td>' . $comment->getComment() . '</td>';
                $table .= '<td>' . $comment->getStatus()  . '</td>';
                $table .= '<td>' . $comment->getNbcon()   . '</td>';
                $table .= '<td>' . '<input type="hidden" name="T$comment" value ="<?php $comment; ?>"/>' . '</td>';
                $table .= '<td><a href="'. HOME .'comment-gest/val-' . $comment->getId() . '-upd' .'"><i class = "fas fa-thumbs-up " alt="Valider commentaire" title = "Validation"></i></a></td>';

                $table .= '<td><a  href="'. HOME . 'comment-gest/del-' . $comment->getId()  . '-del' . '"><i class = "fas fa-comment-slash " alt="Supprimer commentaire" title = "Suppression"></i></a></td>';


                $table .= '<tr>';
            }
            print_r($table);
           
            ?>
             <p>
        <tbody>
    </table>
</div>
