
<?php 
$src= IMG . "plume70";
$alt="crayon";
?>   
<div class= "col-md-1">
  <!--  <img  src="<?php echo $src?>" width=30px height = 30px alt="<?php echo $alt?>" title ="<?php echo $alt?>"> -->
</div>

<div class = "col-md-8 ">
    <div class="row"> 
        <form  action ="<?= HOME . 'index.php' ?>" method = "post">
            
            <div class="row"> 
                <label for="comment" class="mr-2"></label>
                <textarea class="form-control" name = "comment" cols= 90  rows="3" ></textarea wrap="type">
            </div>
            <div class="row">  
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                    <span class="input-group-text">
                        <i class='fas fa-user-secret' style='font-size:24px'></i>
                    </span>   
                    <input type="text" class="form-control mr-2" name="pseudo" required placeholder="pseudo ">
                    </div>
                
                    <div class="input-group-prepend">
                    <span class="input-group-text">@</span>
                    <input type="text" class="form-control mr-2" name="user" placeholder="user">
                    </div>
        
                   <!-- <div class="form-check">        
                    <label class="form-check-label">
                        <input class="form-check-input" type="checkbox">Se rappeler de moi
                    </label>
                    </div> -->
                    <input type="hidden" name="id" value="<?= ''; ?>">
                    <input type="hidden" name="bookId" value="<?= $episode->getBookId(); ?>">
                    <input type="hidden" name="epsId" value="<?= $episode->getId(); ?>">
                    <input type="hidden" name="postDat" value="<?= date("Ymd"); ?>"> 
                    <input type="hidden" name="status" value="<?= '00'; ?>">
                    <input type="hidden" name="validDat" value="<?= ''; ?>">
                    <input type="hidden" name="nbCon" value="<?= '0'; ?>">
                    
                    <?php $opt= 'add'; ?>
                    <input type="hidden" name="url" value ="<?= 'comment/edit-' . $episode->getId() .'-' . $opt ; ?>"> 
                    <input type='hidden' name="action" value ="<?php echo($opt); ?>">
                    <button type="submit" class="btn btn-default btn-xs"><i class='far fa-paper-plane' style='font-size:24px'></i></button>
                </div>
            </div>
        </form>
    </div>
    <div class="row"> 
        <?php (is_array($comments) && !empty($comments)) ?  $x = count($comments) :  $x = 'aucun';?>
       
        <p class="bg-info"><?= $x ?> commentaires</p>
        <section class="row"> 
            <?php
                $this->view_comments = $comments;
                foreach($this->view_comments as $comment)
                {
                    if($comment->getStatus() <> '99') // annulé
                    {
        
                    //   <!-- `id``bookId``bookVol``bookChap``epsId``user``pseudo``comment``postDat``status``validDat` <!--
                        ?>
                        <div class = "col-md-10">
                            <div class="shadow p-4 mb-4 bg-white">
                            <p> <?= $comment->getPseudo() ?> le:<?= $comment->getPostdat() ?></p>
                            <p> <?= $comment->getComment()?></p>
                            <?php if($comment->getNbCon() > 0) : ?>
                                <br>
                                <p> signalé: <?= $comment->getNbCon()?> fois</p>
                                <?php endif; ?>
                            </div>
                        </div>
                        
                        <div class = "col-md-2">
                            <form  action ="<?= HOME . 'index.php' ?>" method = "post">
                                
                                <?php $opt= 'con';?>

                                <input type="hidden" name="id" value="<?= $comment->getId(); ?>">
                                <input type="hidden" name="bookId" value="<?= $comment->getBookId(); ?>">
                                <input type="hidden" name="epsId" value="<?= $comment->getEpsId(); ?>">
                                <input type="hidden" name="comment" value="<?= $comment->getComment(); ?>">
                                <input type="hidden" name="pseudo" value="<?= $comment->getPseudo(); ?>">
                                <input type="hidden" name="user" value="<?= $comment->getUser(); ?>">
                                <input type="hidden" name="postDat" value="<?= $comment->getPostDat(); ?>">
                                <input type="hidden" name="status" value="<?= $comment->getStatus(); ?>">
                                <input type="hidden" name="validDat" value="<?= $comment->getValidDat(); ?>">
                                <?php $comment->addNbcon(); ?>
                                <input type="hidden" name="nbCon" value="<?= $comment->getNbcon(); ?>">
                    
                                <input type="hidden" name="url" value ="<?= 'comment-signal/signal-' . $comment->getBookId() .'.' . $comment->getEpsId() . '.' . $comment->getId() .'-' . $opt ; ?>"> 
                                <input type='hidden' name="action" value ="<?php echo($opt); ?>">
                                <button type="submit">Signaler <br/><i class="fas fa-bell"></i></button>
                            </form>
                            <br />
                            
                       </div>
                    <?php 
                    }           
                }                                                                                                                                                                                                                      
            ?> 
        </section>  
    </div>
</div> 
