<?php

 ?>
<form  action ="<?= HOME . 'index.php' ?>" method = "post">

      
    
 
    <div class="field">
    <label for="userId">Utilisateur</label>
    <input type="text" name="userId" id="userId" value="<?php escape(Input::get('userId')); ?>" autocomplete="off">
    </div>


    <div class="field">
    <label for="password">Mot de passe</label>
    <input type="password" name="password" id="password" value="<?php escape(Input::get('password')); ?>" autocomplete="off">
    </div>

    <div class = "field">
        <label for= "remember">
            <input type="checkbox" name="remember" id ="remember"> Mémoriser
        </label>
    </div>
    <input type="hidden" name="url" value ="user-login"> 
    <input type='hidden' name="action" value ="connect">

    <input type="submit" value="Log in">
    </div>
</form>
