<?php $opt = "register"; ?>
<?php $class = 'class = "form-control form-control-sm"'; ?>

<form  action ="<?= HOME . 'index.php' ?>" method = "post">

<form action = ""  method = "post">
<div class="row">  
<div class = "col-md-6 offset-md-1">
    <div class="form-group">
    
        <label for "userId">Identifiant</label>
        <input <?= $class; ?> type="text" name="userId" id="userId" value="<?php escape(Input::get('userId')); ?>" autocomplete="off">
    </div>

    <div class="form-group">
    <label for "password">Mot de passe</label>
    <input <?= $class; ?> type="password" name="password" id="password" value="<?php escape(Input::get('password')); ?>" autocomplete="off">
    </div>

    <div class="form-group">
    <label for "passwordBis">Confirmer le Mot de passe</label>
    <input <?= $class; ?> type="password" name="passwordBis" id="passwordBis" value="" autocomplete="off">
    </div>

    <div class="form-group">
    <label for "email">Adresse Mail</label>
    <input <?= $class; ?> type="e-mail" name="email" id="email" value="" autocomplete="off">
    </div>

    <div class="field">
    <label for "lastName">Nom</label>
    <input <?= $class; ?> type="text" name="lastName" id="lastName" value="" autocomplete="off">
    </div>

    <div class="field">
    <label for "pseudo">Pseudo</label>
    <input <?= $class; ?> type="text" name="pseudo" id="pseudo" value="" autocomplete="off">
    </div>
   
    <input type="hidden" name="url" value ="<?= 'user/edit-'; ?>"> 
    
    <input type='hidden' name="action" value ="<?php echo($opt); ?>">
    <input type="hidden" name="token" id="token" value="<?php // echo Token::generate(); ?>">
    <input type="submit" value="inscription">
    </div>
    </div>
    </div>
</form>

