<?php include(VIEW . 'header.phtml'); 
if(empty($this->view_data))
{
    var_dump($this->view_data);
    $this->view_data = new Book();
    // $book = new Book();
}
foreach($this->view_data as $book)
{  
?>
<h1> Book management </h1>
<!--SELECT `id``title``plot``onlineDat``nbEps``status``isbn``editYear` FROM `book` -->
<h2> <?=$this->page_title?> </h2>
<form class ="dta-add-class" action ="<?= HOME . 'index.php' ?>" method = "post">
    <div class="input">                 
            <label>Titre </label> :<input type="text" name="title" maxlength="50" value="<?=($book->getId()) > 0 ? $book->getTitle() : ''; ?>">
    </div>
    <div class="input">  
        <label for="plot">résumé</label>
        <textarea  name = "plot" cols= 120 rows = 5 required> <?=($book->getId()) > 0 ? $book->getPlot(): ''; ?> </textarea wrap="type">
    </div>
    <div class="input">  
        <label>Status </label> :<input type="text" name="status" value="<?=($book->getId()) > 0 ? $book->getStatus():''; ?>"maxlength="2">
    </div>
    <div class="input">                 
        <label>ISBN </label> :<input type="text" name="isbn" value="<?=($book->getId()) > 0 ? $book->getIsbn():''; ?>"maxlength="20">
    </div>
    <div class="input">                 
        <label>Année edition </label> :<input type="number" maxlength="4" name="editYear" value="<?=($book->getId()) > 0 ? $book->getEditYear():''; ?>"placeholder="SSAA" maxlength=4>
    </div>
    <div class="input">                 
        <label>Mis en ligne le </label> :<input type="date" maxlength="10" name="onlineDat" value="<?=($book->getId()) > 0 ? $book->getOnlineDat(): ''; ?>">
    </div>
    <div class="input">                 
        <label>Nb épisodes </label> :<input type="number" maxlength="3" name="nbEps" value="<?= ($book->getId()) > 0 ? $book->getnbEps() : ''; ?>">
    </div>
    <input type="hidden" name="id" value="<?= ($book->getId()) > 0 ? $book->getId() :''; ?>">
    <input type='hidden' name="url" value ='<?php echo($book->getId() > 0 ? 'book/maj-':'book/add-') . $book->getId(); ?>'>
    <div class="input">  
        <input type="submit" value ="<?=($book->getId()) > 0 ? 'MODIFIER' : 'AJOUTER'; ?>">
    </div>
</form>

<?php
}
?>


        

        
        

        


<?php include(VIEW . 'footer.phtml'); ?>