<?php 
if(empty($this->view_data))
{
    $this->view_data = new Episode();
    // $episode = new Episode();
}
foreach($this->view_data as $episode)
{  
?>
<h1> Episode management </h1>
<!--SELECT SELECT `id``quote``content``excerpt``createdDat``status``onlineDate``commented``nbComment``bookId``chapter``version``slugEps` from episode  -->
<h2> <?=$this->page_title?> </h2>
<form class ="dta-add-class" action ="<?= HOME . 'index.php' ?>" method = "post">
    <div class="input">                 
            <label>Quote </label> :<input type="text" name="quote" maxlength="50" value="<?=($episode->getQuote()) > 0 ? $episode->getQuote() : ''; ?>">
    </div>
    <div class="input">  
        <label for="content">episode</label>
        <textarea  class="tinymce" name = "content" cols= 200 rows = 10 required> <?=($episode->getContent()) > 0 ? $episode->getContent(): ''; ?> </textarea wrap="type">
    </div>
    <div class="input">  
        <label>Status </label> :<input type="text" name="status" value="<?=($episode->getId()) > 0 ? $episode->getStatus():''; ?>"maxlength="2">
    </div>
    <div class="input">                 
        <label>ISBN </label> :<input type="text" name="isbn" value="<?=($episode->getId()) > 0 ? $episode->getIsbn():''; ?>"maxlength="20">
    </div>
    <div class="input">                 
        <label>Année edition </label> :<input type="number" maxlength="4" name="editYear" value="<?=($episode->getId()) > 0 ? $episode->getEditYear():''; ?>"placeholder="SSAA" maxlength=4>
    </div>
    <div class="input">                 
        <label>Mis en ligne le </label> :<input type="date" maxlength="10" name="onlineDat" value="<?=($episode->getId()) > 0 ? $episode->getOnlineDat(): ''; ?>">
    </div>
    <div class="input">                 
        <label>Nb épisodes </label> :<input type="number" maxlength="3" name="nbEps" value="<?= ($episode->getId()) > 0 ? $episode->getnbEps() : ''; ?>">
    </div>
    <input type="hidden" name="id" value="<?= ($episode->getId()) > 0 ? $episode->getId() :''; ?>">
    <input type='hidden' name="url" value ='<?php echo($episode->getId() > 0 ? 'episode/maj-':'episode/add-') . $episode->getId(); ?>'>
    <div class="input">  
        <input type="submit" value ="<?=($episode->getId()) > 0 ? 'MODIFIER' : 'AJOUTER'; ?>">
    </div>
</form>

<?php
}
?>


        

        
        

        


<?php include(VIEW . 'footer.phtml'); ?>