
<h1> Show episode list </h1>

<!-- `quote``content``excerpt``createdDat``status``onlineDate``commented``nbComment``bookId``chapter``version``slugEps` -->
<div id="container" class="row">
    <table class="table-striped" >
        <thead>
            <tr>
                <th>Chapître</th>
                <th>quote</th>
                <th>extrait</th>
                <th>statut</th>
                <th>Der.commentaire</th>
                <th>voir +</th>
            </tr>
        </thead>
        <tbody>

            <?php 
            $table = '';
            foreach($this->view_data as $episode)
            {                                                                                                                                                                                                                        
                $table .= '<tr>';
                $table .= '<td>' . $episode->getChapter() . '</td>';
                $table .= '<td>' . $episode->getQuote() . '</td>';
                $table .= '<td>' . $episode->getExcerpt() . '</td>';
                $table .= '<td>' . $episode->getStatus() . '</td>';
                $table .= '<td>' . $episode->getCommented()  . '</td>';
  // var_dump('<td><a href= "\"' . HOME . 'episode-show/' . $episode->getBookId() .'-' . $episode->getId() . '>Visu</a></td>');die;

                $table .= '<td><a href=' . HOME . 'episode-show/' . $episode->getBookId() .'-' . $episode->getId() . '>Visu</a></td>';
                $table .= '<td><a href='.'episode-edit/' . $episode->getId() . '-upd' . '>Maj</a></td>';
                $table .= '<td><a href='.'episode-del/' . $episode->getId() . '-del' . '>Del</a></td>';

                $table .= '<tr>';
            }
            print_r($table);
            
            ?>
        <tbody>
    </table>
</div>
