<!-- `quote``content``excerpt``createdDat``status``onlineDate``commented``nbComment``bookId``chapter``version``slugEps` -->
<div id="container-fluid" >
    <div class="row"> 
        <div  class = "col-md-9 offset-1 ">
        <h3> Liste des episodes</h3>
        <br/>
    
        <?php $this->view_episodes = $book->getEpisodes(); ?>
        <?php foreach($this->view_episodes as $episode) : ?> 
            <?php if($episode->getChapter() <> '999') : ?>
                <article class="row">  
                    <div  class = "col-md-3">
                        <?php 
                        $alt = $episode->getImageAlt();
                        $src= IMG125 . $episode->getImage();
                        $epsRef= $episode->getBookId() . '.' . $episode->getVolume() . '.'. $episode->getId();
                        ?>
                        <img  src="<?= $src?>" alt="<?php echo $alt?>" title ="<?php echo $alt?>"> 
                        <a href="<?php echo HOME?>episode-show/show-<?php echo $epsRef?>"><h4>Chapître <?= $episode->getChapter();?></h4></a>
                    </div>
                    <div  class = "col-md-8 offset-1 ">
                        <div class="row">
                                <div class = 'col-md 12'>
                                <blockquote> <?= $episode->getQuote()?></blockquote>
                            </div>
                        </div>
                        <div class="row">
                            <div class = 'col-md 4'>
                                <p> <?= $episode->getExcerpt() ?></p>
                            </div>
                        </div>
                    </div>
                </article>
            <?php endif ?> 
        <?php endforeach ?> 
    </div>
    </div>
</div>
