<!-- `quote``content``excerpt``createdDat``status``onlineDate``commented``nbComment``bookId``chapter``version``slugEps` -->
<div id="container-fluid" >
    <div class="row"> 
        <h3> Liste des episodes</h3>
        <br/>
    </div>
    
    <?php // foreach($this->view_data as $book) :  fait au niveau book/show ?>
    <?php $this->view_episodes = $book->getEpisodes(); ?>
    <?php foreach($this->view_episodes as $episode) : ?>
  
        <?php // $books = $episode->getBookInfo();?>
        <?php // $book = $books[0]; ?>
        <?php $comments = $episode->getComments();?>
        
        <?php if($episode->getChapter() <> '999') : ?>
            <div class="row"> 
        
                <div  class = "col-md-2">
                    <?php 
                    $alt = $episode->getImageAlt();
                    $src= IMG125 . $episode->getImage();
                    $epsRef= $episode->getBookId() . '.' . $episode->getVolume() . '.'. $episode->getId();
                    ?>
                    <img  src="<?= $src?>" alt="<?php echo $alt?>" title ="<?php echo $alt?>"> 
                </div>
                <div  class = "col-md-9 offset-1 ">
                    <div class="row">
                        <div class = 'col-md 2'>
                            <a href="<?php echo HOME?>episode-show/show-<?php echo $epsRef?>"><h3>Chapître <?= $episode->getChapter();?></h3></a>
                        </div>
                        <div class = 'col-md 12'>
                            <h4> <?= $episode->getQuote()?></h4>
                        </div>
                    </div>
                    <div class="row">
                        <div class = 'col-md 4'>
                            <p> <?= $episode->getExcerpt() ?></p>
                        </div>
                    </div>
                </div>
            </div>
        <?php endif ?> 
    <?php endforeach ?> 
    <?php // endforeach ?> 
</div>
