<?php $this->view_data = $datas; ?>
<?php foreach($this->view_data as $episode) :  ?>
<?php // var_dump($this->view_data); die; ?>
    <div class = "container-fluid">
        <?php 
        $books = $episode->getBookInfo(); 
        $book = $books[0]
        ?>
        <?php $comments = $episode->getComments(); 
        ?> 
        
        <?php include (VIEW . 'book\entBook.phtml'); ?>
       
        <?php  $status = $book->getStatus(); ?>     
        <div class = "col-md-10 offset 2">
        
            <div class = "row">
                <?php if($episode->getChapter() <> '999') : ?>
                <h2><?php echo "Chapître..." . $episode->getChapter();?></h2> 
                <?php endif ?>
                <?php if($status === '00')  // Gestion du livre blanc 
                {
                    !$episode->getChapter() === '999' ? $subTitle =  $episode->getQuote() : $subTitle = ''; 
                }else{
                    $subTitle = "Chapître..." . $episode->getChapter();
                }
                 ?>
                  
            </div>
            <div class="row">  
                <div class = "col-md-6 offset-md-2">
                    
                    <blockquote class="blockquote">
                        <p>
                            <b><?php echo $episode->getQuote();?></b>
                        </p>
                    </blockquote>
                
                </div> 

                <?php $alt = $episode->getImageAlt();?>
                <?php $src= IMG215 . $episode->getImage();?>

                <div  class = "col-md-4 ">
                    <div class="thumbnail">
                        <img  src="<?php echo $src?>" class="img-thumbnail" alt="<?php echo $alt?>" title ="<?php echo $alt?>"> 
                        <div class="caption">
                            <p><?php echo $alt?></p>
                        </div>      
                    </div>         
                </div>
            </div>

            <div class="row">
                <div class="entry-content" itemprop="text">
                    <?=  $episode->getContent();?> 
                </div>  
            </div>  

            <?php if($episode->getChapter() <> '999') : ?>
                <div class="row">
                    <?php include (VIEW . 'comment\list.phtml'); ?>
                </div>  
            <?php endif ?>            
        </div>       
            
    </div>  
<?php endforeach ?>
