<?php $this->view_data = $datas; ?>
<?php foreach($this->view_data as $episode) :  ?>
<?php ($episode->getChapter() !== 999) ? $idcontent = 'id ="single-page"' : $idcontent = 'id ="single-page"' ; ?>

    <div class = "container-fluid">
        <?php $book = $episode->getBookInfo();?>
        <?php  $comments = $episode->getComments();  ?>
       
        <?php if($episode->getChapter() !== 999) : include (VIEW . 'book\entBook.phtml'); endif;?>
  
        <div class = "col-md-7 offset-md-1">
            <section   class="entry-content"  <?= $idcontent ?> >
                <div class = "row">
                    <?php if($book->getBlogged() !== 1) : ?>
                            <h2><?php echo "Chapître..." . $episode->getChapter();?></h2> 
                    <?php endif ?>
                                        
                </div>
            
                <div class="row">  
                    <div class = "col-md-6 offset-md-2">
                        
                        <blockquote class="blockquote">
                            <p>
                                <b><?php echo $episode->getQuote();?></b>
                            </p>
                        </blockquote>
                    
                    </div> 

                    <?php $alt = $episode->getImageAlt();?>
                    <?php $src= IMG125 . $episode->getImage();?>

                    <div  class = "col-md-4 ">
                        <div class="thumbnail">
                            <img  src="<?php echo $src?>" class="img-thumbnail" alt="<?php echo $alt?>" title ="<?php echo $alt?>"> 
                            <div class="caption">
                                <p><?php echo $alt?></p>
                            </div>      
                        </div>         
                    </div>
                    
                    <div class = "col-md-8 offset-md-2">
                    <?=  $episode->getContent();?> 
                    </div>
                </div>
            </section>

            <?php if($episode->getChapter() <> '999') : ?>
                <div class="row">
                    <?php include (VIEW . 'comment\list.phtml'); ?>
                </div>  
            <?php endif ?>            
        </div>       
            
    </div>  
<?php endforeach ?>
